apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: correct-gibbon-nodejs 
  janus-idp.io/tekton: correct-gibbon-nodejs
  backstage.io/kubernetes-id: correct-gibbon-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: correct-gibbon-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  